### ISSUE TITLE
tech-debt:  move the repo specific implementations of updating axe-core to this repo

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-api-team-public#30]
See comment: https://github.com/dequelabs/axe-api-team-public/pull/26#discussion_r1326120288

**Comment by straker** [comment]
We already have https://github.com/dequelabs/update-axe-core, but we should port it to this repo and update it to use TypeScript, add tests, and resolve all the open issues. We should also create a composite action that uses it and opens a pr for us as updating axe-core without a pr is kinda useless. Plus every repo that uses the action has to duplicate the pr creation part.
